#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Pilot hosting on the Operator's Mac (issue #10).
#
#   scripts/pilot-setup.sh             set up (or repair) the Pilot copy, step by step
#   scripts/pilot-setup.sh update      move the Pilot copy to the latest release and restart it
#   scripts/pilot-setup.sh check       run the live-site check again (e.g. after a restart)
#   scripts/pilot-setup.sh demo        add the public demo (demo data, no Access) beside the Pilot
#   scripts/pilot-setup.sh demo-reset  reload fresh demo data; launchd runs this every night
#   add --dry-run to any of them to see every command and file without changing the Mac
#
# Every step is safe to repeat: re-running skips or rewrites what is already done.
# ──────────────────────────────────────────────────────────────────────────

MODE=setup
DRY_RUN=0
for arg in "$@"; do
  case "$arg" in
    setup|update|check|demo|demo-reset) MODE="$arg" ;;
    --dry-run) DRY_RUN=1 ;;
    *) printf 'Usage: %s [setup|update|check|demo|demo-reset] [--dry-run]\n' "$0"; exit 2 ;;
  esac
done

REPO_URL="https://github.com/zhipengzhu1-dotcom/10-03-2026-Initial-Launch.git"
BRANCH=main
PILOT_HOST="${PILOT_HOST:-nitrolims-demo.com}"
PILOT_DIR="${PILOT_DIR:-$HOME/Aliquot-Pilot}"
PILOT_DATA="${PILOT_DATA:-$HOME/Aliquot-Pilot-data}"
PILOT_PORT=3000
PILOT_MODULES="samples,methods,instruments,inventory,clients,projects,invoices,portal,insights,team,settings"
STAFF_EMAILS="mara.zhu@botannis.com, zhipengzhu1@gmail.com"
# Everything /portal/ loads: its own files, its API, /js/core/html.js and icons.js, and /assets/favicon.svg.
BYPASS_PATHS=(portal api/portal js/core assets)
TUNNEL_NAME=aliquot-pilot
APP_LABEL=com.aliquot.pilot
TUNNEL_LABEL=com.aliquot.pilot-tunnel
BACKUP_LABEL=com.aliquot.pilot-backup
AGENTS_DIR="$HOME/Library/LaunchAgents"
CF_DIR="$HOME/.cloudflared"
TUNNEL_CONFIG="$CF_DIR/$TUNNEL_NAME.yml"
ICLOUD_ROOT="$HOME/Library/Mobile Documents/com~apple~CloudDocs"
LOCAL_URL="http://127.0.0.1:$PILOT_PORT"
PUBLIC_URL="https://$PILOT_HOST"
GUI="gui/$(id -u)"
# The public demo: a second copy of the same code with the fictional demo lab, open to anyone, reset nightly.
DEMO_HOST="${DEMO_HOST:-app.nitrolims-demo.com}"
DEMO_DATA="${DEMO_DATA:-$HOME/Aliquot-Demo-data}"
DEMO_PORT=3002
DEMO_LABEL=com.aliquot.demo
DEMO_RESET_LABEL=com.aliquot.demo-reset
DEMO_LOCAL_URL="http://127.0.0.1:$DEMO_PORT"
DEMO_URL="https://$DEMO_HOST"
ENV_FILE="$PILOT_DATA/pilot-setup.env"   # values this wizard remembers between runs

DRY_ROOT=""
if (( DRY_RUN )); then
  DRY_ROOT=$(mktemp -d)
  ENV_FILE="$DRY_ROOT/pilot-setup.env"
  open_url() { printf '  %s↗ would open%s %s\n' "$GREEN" "$RESET" "$1"; }
  confirm() { printf '  %s? %s [dry run: yes]%s\n' "$YELLOW" "$1" "$RESET"; }
fi

# run CMD...: show a command that changes the Mac, then run it (a dry run only shows it).
run() {
  printf '  %s$ %s%s\n' "$DIM" "$*" "$RESET"
  (( DRY_RUN )) && return 0
  "$@"
}

# write_file PATH: write stdin to PATH (to a scratch copy in a dry run) and lint it if it's a plist.
write_file() {
  local file="$1" target="$1"
  (( DRY_RUN )) && target="$DRY_ROOT$file"
  mkdir -p "$(dirname "$target")"
  cat > "$target"
  if [[ "$target" == *.plist ]]; then plutil -lint -s "$target"; fi
  printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$file"
  if (( DRY_RUN )); then note "  (dry run: written to $target)"; fi
}

die() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET"; exit 1; }
ok()  { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
bad() { printf '  %s✗%s %s\n' "$RED" "$RESET" "$1"; }

# load_agent LABEL: (re)load a launchd user agent from its plist so changes take effect.
load_agent() {
  run launchctl bootout "$GUI/$1" 2>/dev/null || true
  run launchctl bootstrap "$GUI" "$AGENTS_DIR/$1.plist"
}

agent_running() { [[ "$(launchctl print "$GUI/$1" 2>/dev/null)" == *"state = running"* ]]; }

http_code() { curl -s -o /dev/null --max-time 10 -w '%{http_code}' "$1" || true; }

# wait_for URL SECONDS: poll until URL answers 200.
wait_for() {
  (( DRY_RUN )) && return 0
  local i
  for (( i = 0; i < $2; i++ )); do
    [[ "$(http_code "$1")" == 200 ]] && return 0
    sleep 1
  done
  return 1
}

# setup_state: "needed", "done" or "unknown", asked from this Mac (which counts as local).
setup_state() {
  curl -s --max-time 5 "$LOCAL_URL/api/setup" 2>/dev/null \
    | node -e 'let s="";process.stdin.on("data",(d)=>s+=d).on("end",()=>{try{console.log(JSON.parse(s).needsSetup?"needed":"done")}catch{console.log("unknown")}})'
}

plist_head() {
  cat <<XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$1</string>
XML
}

# plist_env KEY VALUE ...: the entries of a plist's EnvironmentVariables dict.
plist_env() {
  while (( $# )); do printf '    <key>%s</key><string>%s</string>\n' "$1" "$2"; shift 2; done
}

demo_installed() { [[ -f "$DRY_ROOT$AGENTS_DIR/$DEMO_LABEL.plist" ]]; }

# write_tunnel_config: the tunnel's routing, including the demo's hostname once the demo is installed.
write_tunnel_config() {
  write_file "$TUNNEL_CONFIG" <<YAML
# Written by scripts/pilot-setup.sh. Aliquot listens on 127.0.0.1 only.
tunnel: $TUNNEL_ID
credentials-file: $CF_DIR/$TUNNEL_ID.json
ingress:
  - hostname: $PILOT_HOST
    service: http://127.0.0.1:$PILOT_PORT
$(if demo_installed; then printf '  - hostname: %s\n    service: http://127.0.0.1:%s\n' "$DEMO_HOST" "$DEMO_PORT"; fi)
  - service: http_status:404
YAML
  run "$CLOUDFLARED_BIN" tunnel --config "$TUNNEL_CONFIG" ingress validate
}

# route_dns HOST: point HOST at the tunnel, offering to replace an existing record.
route_dns() {
  if ! run "$CLOUDFLARED_BIN" tunnel route dns "$TUNNEL_NAME" "$1"; then
    warn "Cloudflare refused the DNS record, usually because $1 already has an A, AAAA or CNAME record."
    if confirm "Replace the existing $1 record with the tunnel?"; then
      run "$CLOUDFLARED_BIN" tunnel route dns --overwrite-dns "$TUNNEL_NAME" "$1"
    else
      die "Remove the old record in the Cloudflare DNS dashboard, then re-run."
    fi
  fi
  ok "$1 points at the tunnel"
}

# ── The live-site check: the final stage, and `check` mode ────────────────
FAILED=0
expect() { if eval "$2"; then ok "$1"; else bad "$1"; FAILED=$((FAILED + 1)); fi; }

live_site_check() {
  local staff portal lan_ip
  if (( DRY_RUN )); then note "dry run: would query $PUBLIC_URL, the LAN address and the three launchd agents"; return 0; fi
  staff=$(curl -s -o /dev/null --max-time 10 -w '%{http_code} %{redirect_url}' "$PUBLIC_URL/" || true)
  portal=$(curl -s --max-time 10 "$PUBLIC_URL/portal/" || true)
  lan_ip=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)

  say "${BOLD}Automatic checks${RESET}"
  expect "Aliquot service is running"                  "agent_running $APP_LABEL"
  expect "Tunnel service is running"                   "agent_running $TUNNEL_LABEL"
  if [[ -f "$AGENTS_DIR/$BACKUP_LABEL.plist" ]]; then
    expect "Nightly backup job is loaded"              "launchctl print $GUI/$BACKUP_LABEL >/dev/null 2>&1"
  fi
  expect "$PUBLIC_URL/ redirects to Cloudflare Access" '[[ "$staff" =~ ^30[0-9]\ .*cloudflareaccess\.com ]]'
  expect "$PUBLIC_URL/portal/ loads without Access"    '[[ "$portal" == *"<title>Client portal</title>"* ]]'
  expect "/api/portal answers without Access"          '[[ "$(http_code "$PUBLIC_URL/api/portal/info")" == 200 ]]'
  expect "/js/core and /assets load without Access"    '[[ "$(http_code "$PUBLIC_URL/js/core/html.js")" == 200 && "$(http_code "$PUBLIC_URL/assets/favicon.svg")" == 200 ]]'
  expect "The Staff API stays behind Access"           '[[ "$(http_code "$PUBLIC_URL/api/setup")" =~ ^(30[0-9]|401|403)$ ]]'
  if demo_installed; then
    expect "Demo service is running"                   "agent_running $DEMO_LABEL"
    expect "Nightly demo reset is loaded"              "launchctl print $GUI/$DEMO_RESET_LABEL >/dev/null 2>&1"
    expect "$DEMO_URL/ is open without Access"         '[[ "$(http_code "$DEMO_URL/")" == 200 ]]'
    expect "$DEMO_URL/portal/ is open without Access"  '[[ "$(http_code "$DEMO_URL/portal/")" == 200 ]]'
  fi
  if [[ -n "$lan_ip" ]]; then
    expect "Port $PILOT_PORT is closed to the LAN ($lan_ip)" '[[ "$(curl -s -o /dev/null --max-time 3 -w "%{http_code}" "http://$lan_ip:$PILOT_PORT/" || true)" == 000 ]]'
  else
    warn "no Wi-Fi or Ethernet address found, so the LAN check was skipped"
  fi
  printf '\n'
  say "${BOLD}Checks only you can do${RESET}"
  step "In a private browser window, open $PUBLIC_URL, enter an allowlisted email and the code"
  step "  Cloudflare emails you: you reach the Aliquot sign-in page."
  step "Before the first Administrator existed, $PUBLIC_URL said setup has to be done on the"
  step "  computer that runs Aliquot (the first-time setup stage asks you to look)."
  step "Restart the Mac, log in, wait a minute, then run: scripts/pilot-setup.sh check"
  if [[ -f "$AGENTS_DIR/$BACKUP_LABEL.plist" ]]; then
    step "Tomorrow morning, today's aliquot-<date>.db is in the iCloud backups folder:"
    note "    ${ICLOUD_BACKUP_DIR:-$ICLOUD_ROOT/Aliquot-Pilot-backups}/backups"
  fi
  printf '\n'
  if (( FAILED )); then warn "$FAILED automatic check(s) failed: fix them before inviting anyone"; else ok "All automatic checks passed"; fi
}

# ── `check` mode ──────────────────────────────────────────────────────────
if [[ "$MODE" == check ]]; then
  ICLOUD_BACKUP_DIR=$(_existing ICLOUD_BACKUP_DIR || true)
  printf '\n%s%s  Live-site check: %s%s\n\n' "$BOLD" "$BLUE" "$PUBLIC_URL" "$RESET"
  live_site_check
  exit $(( FAILED ? 1 : 0 ))
fi

# ── `update` mode: move the Pilot copy to the latest release ─────────────
if [[ "$MODE" == update ]]; then
  printf '\n%s%s  Update the Pilot copy%s\n\n' "$BOLD" "$BLUE" "$RESET"
  [[ -d "$PILOT_DIR/.git" ]] || die "No Pilot copy at $PILOT_DIR. Run scripts/pilot-setup.sh first."
  [[ -z "$(git -C "$PILOT_DIR" status --porcelain)" ]] || die "$PILOT_DIR has local changes. The Pilot copy must match a release exactly: discard them first."
  git -C "$PILOT_DIR" fetch --quiet origin "$BRANCH"
  before=$(git -C "$PILOT_DIR" rev-parse HEAD)
  if [[ "$before" == "$(git -C "$PILOT_DIR" rev-parse "origin/$BRANCH")" ]]; then
    ok "Already on the latest release: $(git -C "$PILOT_DIR" log -1 --format='%h %s')"
    exit 0
  fi
  say "New in this release:"
  git -C "$PILOT_DIR" log --oneline "HEAD..origin/$BRANCH" | sed 's/^/    /'
  printf '\n'
  confirm "Back up the Pilot data, update and restart Aliquot now (about 10 seconds offline)?" || exit 0
  (cd "$PILOT_DIR" && run env ALIQUOT_DATA="$PILOT_DATA" node scripts/backup.js)
  run git -C "$PILOT_DIR" merge --ff-only --quiet "origin/$BRANCH"
  run launchctl kickstart -k "$GUI/$APP_LABEL"
  (( DRY_RUN )) || sleep 2
  if wait_for "$LOCAL_URL/api/setup" 30; then
    ok "Aliquot restarted on $(git -C "$PILOT_DIR" log -1 --format='%h %s')"
    exit 0
  fi
  bad "Aliquot didn't come back. Last lines of its log:"
  tail -n 20 "$PILOT_DATA/logs/aliquot.log" | sed 's/^/    /'
  note "To roll back: git -C \"$PILOT_DIR\" reset --hard $before && launchctl kickstart -k $GUI/$APP_LABEL"
  note "If the new release migrated the database, also restore the backup just made in $PILOT_DATA/backups/manual-*."
  exit 1
fi

# ── `demo-reset` mode: launchd runs this nightly to reload fresh demo data ─
# reset_demo: stop the demo, wipe its lab, load the demo lab again and start it.
reset_demo() {
  local node_bin="${NODE_BIN:-$(command -v node)}"
  run launchctl bootout "$GUI/$DEMO_LABEL" 2>/dev/null || true
  run rm -rf "$DEMO_DATA/aliquot.db" "$DEMO_DATA/aliquot.db-wal" "$DEMO_DATA/aliquot.db-shm" "$DEMO_DATA/files" "$DEMO_DATA/backups"
  run mkdir -p "$DEMO_DATA/files" "$DEMO_DATA/logs"
  (cd "$PILOT_DIR" && run env ALIQUOT_DATA="$DEMO_DATA" "$node_bin" scripts/seed-demo.js)
  run launchctl bootstrap "$GUI" "$AGENTS_DIR/$DEMO_LABEL.plist"
}

if [[ "$MODE" == demo-reset ]]; then
  demo_installed || die "The demo isn't installed. Run scripts/pilot-setup.sh demo first."
  printf '%s demo reset\n' "$(date '+%Y-%m-%d %H:%M:%S')"
  reset_demo
  wait_for "$DEMO_LOCAL_URL/api/setup" 30 || die "The demo didn't come back after the reset."
  ok "Fresh demo data at $DEMO_URL"
  exit 0
fi

# ── `demo` mode: the public demo beside the Pilot ─────────────────────────
if [[ "$MODE" == demo ]]; then
  printf '\n%s%s  Public demo: %s%s\n\n' "$BOLD" "$BLUE" "$DEMO_URL" "$RESET"
  say "A second copy of Aliquot with the fictional demo lab, open to anyone without Cloudflare Access."
  say "Visitors pick a demo person on either sign-in screen (password demo1234). It shows the Pilot's"
  say "Shipped modules, uses its own data folder, and reloads fresh demo data every night at 03:00."
  note "  data: $DEMO_DATA (never the Pilot's data) · 127.0.0.1:$DEMO_PORT · same code as $PILOT_DIR"
  printf '\n'
  [[ -f "$PILOT_DIR/scripts/seed-demo.js" ]] || die "$PILOT_DIR has no scripts/seed-demo.js. Run scripts/pilot-setup.sh update first."
  TUNNEL_ID=$(_existing TUNNEL_ID || true)
  (( DRY_RUN )) && TUNNEL_ID=${TUNNEL_ID:-00000000-0000-0000-0000-000000000000}
  [[ -n "$TUNNEL_ID" ]] && { (( DRY_RUN )) || [[ -f "$TUNNEL_CONFIG" ]]; } || die "The Pilot's tunnel isn't set up yet. Run scripts/pilot-setup.sh first."
  NODE_BIN=$(command -v node) || die "Node.js is missing."
  CLOUDFLARED_BIN=$(command -v cloudflared || echo /opt/homebrew/bin/cloudflared)
  confirm "Anyone on the internet can use and change the demo until its nightly reset. Set it up?" || exit 0
  TOTAL_STAGES=3

  stage "Demo service"
  write_file "$AGENTS_DIR/$DEMO_LABEL.plist" <<XML
$(plist_head "$DEMO_LABEL")
  <key>ProgramArguments</key>
  <array><string>$NODE_BIN</string><string>$PILOT_DIR/server.js</string></array>
  <key>WorkingDirectory</key><string>$PILOT_DIR</string>
  <key>EnvironmentVariables</key>
  <dict>
$(plist_env PORT "$DEMO_PORT" HOST 127.0.0.1 ALIQUOT_DATA "$DEMO_DATA" SECURE_COOKIES 1 CLOUDFLARE_TUNNEL 1 SHIPPED_MODULES "$PILOT_MODULES")
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ThrottleInterval</key><integer>10</integer>
  <key>StandardOutPath</key><string>$DEMO_DATA/logs/aliquot.log</string>
  <key>StandardErrorPath</key><string>$DEMO_DATA/logs/aliquot.log</string>
</dict>
</plist>
XML
  holder=$(lsof -nP -iTCP:"$DEMO_PORT" -sTCP:LISTEN -t 2>/dev/null | head -n1 || true)
  if [[ -n "$holder" ]] && ! agent_running "$DEMO_LABEL"; then
    die "Port $DEMO_PORT is taken by: $(ps -p "$holder" -o command= | cut -c1-80). Stop it and re-run."
  fi
  run mkdir -p "$DEMO_DATA"
  run chmod 700 "$DEMO_DATA"
  reset_demo
  wait_for "$DEMO_LOCAL_URL/api/setup" 30 || die "The demo didn't start. See $DEMO_DATA/logs/aliquot.log."
  ok "The demo answers at $DEMO_LOCAL_URL"

  stage "Nightly demo reset"
  write_file "$AGENTS_DIR/$DEMO_RESET_LABEL.plist" <<XML
$(plist_head "$DEMO_RESET_LABEL")
  <key>ProgramArguments</key>
  <array><string>/bin/bash</string><string>$PILOT_DIR/scripts/pilot-setup.sh</string><string>demo-reset</string></array>
  <key>EnvironmentVariables</key>
  <dict>
$(plist_env NODE_BIN "$NODE_BIN" PATH "/usr/bin:/bin:/usr/sbin:/sbin:$(dirname "$NODE_BIN")")
  </dict>
  <key>StartCalendarInterval</key>
  <dict><key>Hour</key><integer>3</integer><key>Minute</key><integer>0</integer></dict>
  <key>StandardOutPath</key><string>$DEMO_DATA/logs/reset.log</string>
  <key>StandardErrorPath</key><string>$DEMO_DATA/logs/reset.log</string>
</dict>
</plist>
XML
  load_agent "$DEMO_RESET_LABEL"
  ok "Fresh demo data every night at 03:00 (log: $DEMO_DATA/logs/reset.log)"

  stage "Publish $DEMO_HOST"
  write_tunnel_config
  route_dns "$DEMO_HOST"
  run launchctl kickstart -k "$GUI/$TUNNEL_LABEL"
  say "Waiting for $DEMO_URL/portal/ to answer…"
  if wait_for "$DEMO_URL/portal/" 120; then ok "$DEMO_URL is live"; else warn "$DEMO_URL isn't answering yet; DNS can take a few minutes. Re-check with: scripts/pilot-setup.sh check"; fi
  note "No Access application may cover $DEMO_HOST. If $DEMO_URL asks for an email code, delete that"
  note "application in Zero Trust → Access controls → Applications (the Pilot's two stay as they are)."
  printf '\n'
  say "${BOLD}Staff app:${RESET}      $DEMO_URL/"
  say "${BOLD}Client portal:${RESET}  $DEMO_URL/portal/"
  note "Both sign-in screens list demo people: click one (password demo1234)."
  exit 0
fi

# ── Full setup ────────────────────────────────────────────────────────────
TOTAL_STAGES=12

banner "Aliquot Pilot on this Mac: $PUBLIC_URL"
if (( DRY_RUN )); then warn "DRY RUN: commands are shown, not run; files go to $DRY_ROOT"; fi

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Check this Mac"
[[ "$(uname -s)" == Darwin ]] || die "This setup is for macOS (launchd, pmset, iCloud Drive)."
command -v git >/dev/null || die "git is missing. Install the Xcode command line tools: xcode-select --install"
NODE_BIN=$(command -v node || true)
[[ -n "$NODE_BIN" ]] || die "Node.js is missing. Install Node 22.13 or later (https://nodejs.org or: brew install node)."
"$NODE_BIN" -e 'const [a, b] = process.versions.node.split(".").map(Number); process.exit(a > 22 || (a === 22 && b >= 13) ? 0 : 1)' \
  || die "Node $("$NODE_BIN" --version) is too old: Aliquot needs 22.13 or later."
ok "Node $("$NODE_BIN" --version) at $NODE_BIN"
if [[ "$NODE_BIN" == */.nvm/* || "$NODE_BIN" == */.volta/* || "$NODE_BIN" == */.asdf/* ]]; then
  warn "This Node comes from a version manager. If you switch or remove that version, re-run this wizard."
fi
if ! command -v cloudflared >/dev/null; then
  command -v brew >/dev/null || die "cloudflared is missing and so is Homebrew. Install Homebrew (https://brew.sh), then re-run."
  confirm "cloudflared (Cloudflare's tunnel program) is missing. Install it with Homebrew?" || die "cloudflared is required."
  run brew install cloudflared
fi
CLOUDFLARED_BIN=$(command -v cloudflared || echo "$(brew --prefix 2>/dev/null || echo /opt/homebrew)/bin/cloudflared")
ok "cloudflared at $CLOUDFLARED_BIN"
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Pilot copy and data folder"
say "The Pilot runs from its own checkout and data folder, so your development copy"
say "(port 3001, data-dev/) never changes what the Pilot lab uses."
note "  code: $PILOT_DIR"
note "  data: $PILOT_DATA"
case "$PILOT_DATA/" in "$PILOT_DIR/"*) die "The data folder must be outside the Pilot copy." ;; esac
if [[ -d "$PILOT_DIR/.git" ]]; then
  [[ "$(git -C "$PILOT_DIR" remote get-url origin)" == "$REPO_URL" ]] || die "$PILOT_DIR is a checkout of another repository."
  ok "The Pilot copy already exists. To move it to a new release: scripts/pilot-setup.sh update"
elif [[ -e "$PILOT_DIR" ]]; then
  die "$PILOT_DIR exists but isn't a git checkout. Move it aside and re-run."
else
  if ! git ls-remote --exit-code "$REPO_URL" "$BRANCH" >/dev/null 2>&1; then
    msg="Can't read $REPO_URL. Sign in to GitHub first (gh auth login, then gh auth setup-git) and re-run."
    if (( DRY_RUN )); then warn "$msg"; else die "$msg"; fi
  fi
  run git clone --quiet --branch "$BRANCH" "$REPO_URL" "$PILOT_DIR"
fi
run mkdir -p "$PILOT_DATA/logs" "$PILOT_DATA/files"
run chmod 700 "$PILOT_DATA"
ok "Data folder ready: the database, files/, backups/ and logs/ live here"
pause "Press Enter to continue"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Aliquot as a service"
say "A launchd agent starts Aliquot when you log in and restarts it if it stops."
note "  127.0.0.1:$PILOT_PORT only · secure cookies · behind Cloudflare Tunnel · Pilot modules"
write_file "$AGENTS_DIR/$APP_LABEL.plist" <<XML
$(plist_head "$APP_LABEL")
  <key>ProgramArguments</key>
  <array><string>$NODE_BIN</string><string>$PILOT_DIR/server.js</string></array>
  <key>WorkingDirectory</key><string>$PILOT_DIR</string>
  <key>EnvironmentVariables</key>
  <dict>
$(plist_env PORT "$PILOT_PORT" HOST 127.0.0.1 ALIQUOT_DATA "$PILOT_DATA" SECURE_COOKIES 1 CLOUDFLARE_TUNNEL 1 SHIPPED_MODULES "$PILOT_MODULES")
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ThrottleInterval</key><integer>10</integer>
  <key>StandardOutPath</key><string>$PILOT_DATA/logs/aliquot.log</string>
  <key>StandardErrorPath</key><string>$PILOT_DATA/logs/aliquot.log</string>
</dict>
</plist>
XML
run launchctl bootout "$GUI/$APP_LABEL" 2>/dev/null || true
(( DRY_RUN )) || sleep 1
holder=$(lsof -nP -iTCP:"$PILOT_PORT" -sTCP:LISTEN -t 2>/dev/null | head -n1 || true)
if [[ -n "$holder" ]]; then
  msg="Port $PILOT_PORT is taken by: $(ps -p "$holder" -o command= | cut -c1-80). Stop it (development uses 3001) and re-run."
  if (( DRY_RUN )); then warn "$msg"; else die "$msg"; fi
fi
run launchctl bootstrap "$GUI" "$AGENTS_DIR/$APP_LABEL.plist"
if wait_for "$LOCAL_URL/api/setup" 30; then
  ok "Aliquot answers at $LOCAL_URL"
else
  bad "Aliquot didn't start. Last lines of $PILOT_DATA/logs/aliquot.log:"
  tail -n 20 "$PILOT_DATA/logs/aliquot.log" | sed 's/^/    /'
  die "Fix the error above and re-run."
fi
pause "Press Enter to continue"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Keep the Mac awake on power"
say "The Pilot is down whenever the Mac sleeps. This turns sleep off while it's plugged in;"
say "on battery it still sleeps. macOS asks for your admin password."
ac_sleep=$(pmset -g custom 2>/dev/null | awk '/^AC Power/{ac=1} /^Battery Power/{ac=0} ac && $1=="sleep"{print $2}' || true)
if [[ "$ac_sleep" == 0 ]]; then
  ok "Sleep is already off on power"
elif confirm "Turn off sleep on power (sudo pmset -c sleep 0)?"; then
  run sudo pmset -c sleep 0
  ok "Sleep is off on power"
else
  SKIPPED+=("sleep on power: run sudo pmset -c sleep 0")
fi
note "Closing the lid still sleeps the Mac unless an external display is attached, so keep it open."
if [[ "$(fdesetup status 2>/dev/null || true)" == *"is On"* ]]; then
  note "FileVault is on, so after a restart someone must log in before Aliquot and the tunnel start."
else
  note "After a restart the services start at login. For a hands-free restart, turn on automatic login:"
  note "System Settings → Users & Groups → Automatically log in as."
fi
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare: sign in"
say "cloudflared needs permission to manage tunnels for $PILOT_HOST,"
say "which must already be an active domain in your Cloudflare account."
if [[ -f "$CF_DIR/cert.pem" ]]; then
  ok "Already signed in ($CF_DIR/cert.pem exists)"
else
  step "A browser window opens. Sign in to Cloudflare, click $PILOT_HOST, then Authorize."
  step "Come back here once the page says the credentials were installed."
  pause "Press Enter to open the sign-in"
  run "$CLOUDFLARED_BIN" tunnel login
  [[ -f "$CF_DIR/cert.pem" ]] || (( DRY_RUN )) || die "Sign-in didn't finish ($CF_DIR/cert.pem is missing). Re-run to try again."
  ok "Signed in"
fi
pause "Press Enter to continue"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare Access: guard the Staff app"
say "Access goes in before the tunnel publishes the site."
note "Cloudflare renames dashboard items from time to time; pick the closest match."
open_url "https://one.dash.cloudflare.com/"
step "First visit only: choose a team name and the Free plan when asked."
step "Settings → Authentication → Login methods: make sure ${BOLD}One-time PIN${RESET} is listed"
step "  (if not: Add new → One-time PIN → Save)."
step "Access → Applications → Add an application → ${BOLD}Self-hosted${RESET}."
step "Application name ${BOLD}Aliquot Staff app${RESET}; domain ${BOLD}$PILOT_HOST${RESET} with the path left empty."
step "Add a policy: name ${BOLD}Pilot staff${RESET}, action ${BOLD}Allow${RESET}, Include → Emails:"
step "  ${BOLD}$STAFF_EMAILS${RESET}"
step "Login methods: turn off \"accept all available identity providers\" and select only One-time PIN."
step "Save the application."
note "Later, add each Pilot lab staff email to this policy before creating their Aliquot account."
pause "Press Enter once the Staff app is saved"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare Access: let clients reach the portal"
say "Clients aren't on the allowlist: the Client portal has its own sign-in. A second"
say "application with a Bypass policy opens exactly what the portal page loads."
open_url "https://one.dash.cloudflare.com/"
step "Access → Applications → Add an application → ${BOLD}Self-hosted${RESET}."
step "Application name ${BOLD}Aliquot Client portal${RESET}."
step "Add one domain entry per path, each on ${BOLD}$PILOT_HOST${RESET}:"
for p in "${BYPASS_PATHS[@]}"; do step "  path ${BOLD}$p${RESET}"; done
step "Add a policy: name ${BOLD}Client portal${RESET}, action ${BOLD}Bypass${RESET}, Include → ${BOLD}Everyone${RESET}."
step "Save the application."
note "Access applies the most specific path, so these paths skip Access and everything else"
note "on $PILOT_HOST stays behind the Staff app's policy."
pause "Press Enter once the Client portal application is saved"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Tunnel and DNS record"
say "A named tunnel carries $PUBLIC_URL to Aliquot on this Mac, with no port opened."
tunnel_id() {
  "$CLOUDFLARED_BIN" tunnel list --name "$TUNNEL_NAME" --output json 2>/dev/null \
    | node -e 'let s="";process.stdin.on("data",(d)=>s+=d).on("end",()=>{const t=(JSON.parse(s||"[]")||[])[0];if(t)console.log(t.id)})'
}
if (( DRY_RUN )); then
  TUNNEL_ID=00000000-0000-0000-0000-000000000000
  run "$CLOUDFLARED_BIN" tunnel create "$TUNNEL_NAME"
else
  TUNNEL_ID=$(tunnel_id || true)
  if [[ -z "$TUNNEL_ID" ]]; then
    run "$CLOUDFLARED_BIN" tunnel create "$TUNNEL_NAME"
    TUNNEL_ID=$(tunnel_id || true)
  fi
  [[ -n "$TUNNEL_ID" ]] || die "Couldn't find or create the tunnel $TUNNEL_NAME."
fi
ok "Tunnel $TUNNEL_NAME ($TUNNEL_ID)"
write_env TUNNEL_ID "$TUNNEL_ID"
if [[ ! -f "$CF_DIR/$TUNNEL_ID.json" ]]; then
  note "This Mac has no credentials for the tunnel yet (it was created elsewhere): fetching them."
  run "$CLOUDFLARED_BIN" tunnel token --cred-file "$CF_DIR/$TUNNEL_ID.json" "$TUNNEL_NAME"
fi
write_tunnel_config
route_dns "$PILOT_HOST"
pause "Press Enter to continue"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Tunnel as a service"
say "A second launchd agent keeps cloudflared connected from login on, restarting it if it stops."
write_file "$AGENTS_DIR/$TUNNEL_LABEL.plist" <<XML
$(plist_head "$TUNNEL_LABEL")
  <key>ProgramArguments</key>
  <array><string>$CLOUDFLARED_BIN</string><string>tunnel</string><string>--no-autoupdate</string><string>--config</string><string>$TUNNEL_CONFIG</string><string>run</string><string>$TUNNEL_NAME</string></array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ThrottleInterval</key><integer>10</integer>
  <key>StandardOutPath</key><string>$PILOT_DATA/logs/cloudflared.log</string>
  <key>StandardErrorPath</key><string>$PILOT_DATA/logs/cloudflared.log</string>
</dict>
</plist>
XML
load_agent "$TUNNEL_LABEL"
say "Waiting for $PUBLIC_URL/portal/ to answer (a new DNS record can take a minute)…"
if wait_for "$PUBLIC_URL/portal/" 120; then
  ok "$PUBLIC_URL is live"
else
  warn "$PUBLIC_URL/portal/ isn't answering yet. Last lines of the tunnel log:"
  tail -n 10 "$PILOT_DATA/logs/cloudflared.log" 2>/dev/null | sed 's/^/    /'
  note "If DNS is still spreading, carry on: the final stage checks again."
fi
pause "Press Enter to continue"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "First-time setup"
state=unknown
(( DRY_RUN )) || state=$(setup_state)
if [[ "$state" == done ]]; then
  ok "Aliquot is already set up: the first Administrator exists."
else
  say "First, see that nobody on the internet can claim the Administrator account:"
  open_url "$PUBLIC_URL/"
  step "Enter an allowlisted email, then the code Cloudflare emails you."
  step "Aliquot should say it isn't set up yet and that setup has to be done on the computer"
  step "that runs Aliquot."
  if confirm "Did it show that message?"; then
    ok "Setup is locked at the public address"
  else
    SKIPPED+=("setup lock at $PUBLIC_URL not confirmed: check CLOUDFLARE_TUNNEL=1 in $AGENTS_DIR/$APP_LABEL.plist")
  fi
  printf '\n'
  say "Now create the first Administrator here, on this Mac:"
  open_url "http://localhost:$PILOT_PORT/"
  step "Fill in the laboratory name, your name, a username and a strong password, then create."
  step "No demo data option appears: demo accounts never exist behind the tunnel."
  note "Safari may not keep you signed in on http://localhost (secure cookies); sign in at $PUBLIC_URL instead."
  pause "Press Enter once the Administrator is created"
  (( DRY_RUN )) || state=$(setup_state)
  if [[ "$state" == done ]] || (( DRY_RUN )); then
    ok "First Administrator created"
  else
    SKIPPED+=("first-time setup: open http://localhost:$PILOT_PORT on this Mac and create the Administrator")
    warn "Aliquot still has no Administrator; finish it later at http://localhost:$PILOT_PORT"
  fi
fi
pause "Press Enter to continue"

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Nightly backup to iCloud Drive"
say "Aliquot snapshots its database into $PILOT_DATA/backups every day and keeps 14."
say "A nightly job at 02:30 copies those snapshots and the attached files to iCloud Drive."
while [[ ! -d "$ICLOUD_ROOT" ]] && (( ! DRY_RUN )); do
  warn "iCloud Drive isn't on for this Mac user."
  step "System Settings → your name → iCloud → iCloud Drive → turn on \"Sync this Mac\"."
  pause "Press Enter once iCloud Drive is on"
done
ask ICLOUD_BACKUP_DIR "iCloud folder for backups (Enter for $ICLOUD_ROOT/Aliquot-Pilot-backups):"
ICLOUD_BACKUP_DIR="${ICLOUD_BACKUP_DIR:-$ICLOUD_ROOT/Aliquot-Pilot-backups}"
write_env ICLOUD_BACKUP_DIR "$ICLOUD_BACKUP_DIR"
run mkdir -p "$ICLOUD_BACKUP_DIR"
write_file "$AGENTS_DIR/$BACKUP_LABEL.plist" <<XML
$(plist_head "$BACKUP_LABEL")
  <key>ProgramArguments</key>
  <array><string>/usr/bin/rsync</string><string>-a</string><string>$PILOT_DATA/backups</string><string>$PILOT_DATA/files</string><string>$ICLOUD_BACKUP_DIR/</string></array>
  <key>StartCalendarInterval</key>
  <dict><key>Hour</key><integer>2</integer><key>Minute</key><integer>30</integer></dict>
  <key>StandardOutPath</key><string>$PILOT_DATA/logs/backup.log</string>
  <key>StandardErrorPath</key><string>$PILOT_DATA/logs/backup.log</string>
</dict>
</plist>
XML
note "The copy only adds: older snapshots stay in iCloud until you delete them."
load_agent "$BACKUP_LABEL"
say "Running the job once now to prove it works…"
run launchctl kickstart "$GUI/$BACKUP_LABEL"
(( DRY_RUN )) || sleep 5
if (( DRY_RUN )) || compgen -G "$ICLOUD_BACKUP_DIR/backups/aliquot-*.db" >/dev/null; then
  ok "Snapshot copied to $ICLOUD_BACKUP_DIR/backups"
else
  bad "No snapshot arrived. Last lines of $PILOT_DATA/logs/backup.log:"
  tail -n 10 "$PILOT_DATA/logs/backup.log" 2>/dev/null | sed 's/^/    /'
  note "\"Operation not permitted\" means macOS blocked background access to iCloud Drive: open"
  note "System Settings → Privacy & Security → Full Disk Access → + → Cmd-Shift-G → /usr/bin/rsync,"
  note "then run: launchctl kickstart $GUI/$BACKUP_LABEL"
  SKIPPED+=("the first iCloud backup copy didn't arrive (see $PILOT_DATA/logs/backup.log)")
fi
pause "Press Enter to continue"

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Live-site check"
live_site_check
if (( FAILED )); then SKIPPED+=("$FAILED live-site check(s) failed: fix them, then run scripts/pilot-setup.sh check"); fi
pause "Press Enter to finish"

finish
say "To move the Pilot to a new release:  scripts/pilot-setup.sh update"
say "To repeat the live-site check:       scripts/pilot-setup.sh check"
say "Logs: $PILOT_DATA/logs/"
printf '\n'
